//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int id { get; set; }
        public int goodId { get; set; }
        public string city { get; set; }
    
        public virtual Good Good { get; set; }
    }
}
